services:
  birthday_bot:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: birthday_bot
    restart: always
    env_file:
      - ../.env
    depends_on:
      - birthday_db
    
  
  birthday_db:
    image: postgres:15-alpine
    container_name: birthday_db
    restart: always
    env_file:
      - ../.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  birthday_db_data: